# Generated by Django 4.0.2 on 2022-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='car',
            name='trees',
            field=models.ManyToManyField(to='main_app.Tree'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='date',
            field=models.DateField(verbose_name='fill date'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='fill',
            field=models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4')], default='1', max_length=1),
        ),
    ]
