# Generated by Django 4.0.2 on 2022-03-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
